on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '\d+\.\d+\.\d+'

name: Publish to Pypi

jobs:
  deploy:
    name: Deploy to PYPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/metar-taf-parser-mivek/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install_deploy

      - name: Build the archives
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
